disable_existing_loggers: false
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
  file:
    backupCount: 1
    class: logging.handlers.RotatingFileHandler
    filename: edrp.log
    formatter: simple
    maxBytes: 1000000
    mode: a
loggers:
  simple:
    handlers:
    - console
    - file
    propagate: false
root:
  handlers:
  - console
  - file
  level: DEBUG
version: 1
