name: Licensed CI

on:
  workflow_dispatch:

jobs:
  update_license:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true # improve performance on subsequent runs
          cache-version: 1
      - uses: actions/setup-python@v3.1.2
        with:
          python-version: "3.10"
          cache: pip # cache dependencies for faster subsequent runs.
          cache-dependency-path: requirements.txt
      # install your projects dependencies
      - id: licensed
        uses: jonabc/licensed-ci@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          command: bundle exec licensed # or bin/licensed when using binstubs
      - uses: actions/github-script@0.2.0
        if: always() && steps.licensed.outputs.pr_number
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              ...context.repo,
              issue_number: ${{ steps.licensed.outputs.pr_number }}
              body: 'My custom PR message'
            })
